baseURL = "https://blog.softwarestable.com/"
languageCode = "en-us"
title = "SoftwareStable Blog" # Your Blog Title
#theme = "" # Ensure this is empty or commented out
paginate = 5 # Number of posts per page on list pages

# Parameters used in templates
[params]
  description = "Thoughts and articles from SoftwareStable."
  # Optional: Define a default date format if needed
  # dateFormat = "Jan 2, 2006"
  mainSections = ["posts"] # Crucial for pagination to find posts

# Enable RSS Feed generation
[outputs]
  home = ["HTML", "RSS"]

# Enable taxonomies (like tags)
[taxonomies]
  tag = "tags"
  # category = "categories"

# --- CORRECT AND CONSOLIDATED MARKUP CONFIGURATION ---
[markup]
  # Table of Contents Settings (Example)
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

  # Syntax Highlighting Settings
  [markup.highlight]
    # Set noClasses = false if you want Hugo to add CSS classes for syntax highlighting
    # You would then need to add a Hugo syntax highlighting CSS theme file
    noClasses = true

  # Goldmark Markdown Renderer Settings
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true # Enable {% attr %} markup
      autoHeadingID = true
      autoHeadingIDType = "github"
    # Renderer settings nested correctly here
    [markup.goldmark.renderer]
      hardWraps = false
      # Allow raw HTML in markdown content (e.g., for iframe embeds)
      unsafe = true # <--- This is the critical key within the renderer table
      xhtml = false

# Enable calculation of Reading Time for posts
enableGitInfo = false
hasCJKLanguage = false